### ISSUE TITLE
Wifi module features not working.

### ISSUE THREAD

**Issue by liouma** [jeggleston1981/easy_skyfanDC#2]
Hello, I just received the wifi modules I ordered.
I can switch on/off the fan and light, can not adjust fan speed or light brightness.
In ESPhome I can see the following yaml configuration:

```
substitutions:
  name: "fan-bureau"
packages:
  jimmy.easy_skyfandc: github://jeggleston1981/skyfandc/micro_skyfan2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: WGY7qr5jJgCEepjBTXRlmsUyVc9uq3mo8YmkQ5+brx4=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
The referenced file is .../skyfanDC/... instead of .../easy_skyfanDC/... is it normal?
Should I update the file in esphome ?
